### ISSUE TITLE
Adding a way to delete objects

### ISSUE THREAD

**Issue by PhilippAuch** [TobiasBodewig/Ludum-Dare-30#18]
Logic Objects for example. Can you delete them?

**Comment by TobiasBodewig** [comment]
Yes, select them and pres Entf/Del.

**Comment by PhilippAuch** [comment]
There's no way to select LogicObjects for me...

**Comment by TobiasBodewig** [comment]
1. Go into Logic-Mode.
2. Left-Click the LogicObject
3. Pres [Entf]/[Del].

**Comment by PhilippAuch** [comment]
Not working for me ....
